version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: playerdata-db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ../.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres-network
      
networks:
  postgres-network:
    driver: bridge

volumes:
  postgres:
    name: nest-db
