export const CACHE_TTL = {
  LOCAL_FINDONE: 60,
  LOCAL_FINDALL: 300,
  DISTRIBUTED_FINDONE: 600,
  DISTRIBUTED_FINDALL: 3600,
};

export const CACHE_KEYS = {
  ALL_PROFILES: 'player_profiles:all',
  PROFILE: (uuid: string) => `player_profile:${uuid}`,
  PROFILES_LIST: 'player_profiles:list',
  ALL_OBTAINBASES: 'obtainbases:all',
  OBTAINBASE_ITEM: (uuid: string) => `obtainbase:item:${uuid}`,
  OBTAINBASES_LIST: 'obtainbases:list',
  ALL_CONSUMEBASES: 'consumebases:all',
  CONSUMEBASE_ITEM: (uuid: string) => `consumebase:item:${uuid}`,
  CONSUMEBASES_LIST: 'consumebases:list',
  ALL_AVATARBASES: 'avatarbases:all',
  AVATARBASE_ITEM: (uuid: string) => `avatarbase:item:${uuid}`,
  AVATARBASES_LIST: 'avatarbases:list',
  ALL_FRAMEBASES: 'framebases:all',
  FRAMEBASE_ITEM: (uuid: string) => `framebase:item:${uuid}`,
  FRAMEBASES_LIST: 'framebases:list',
  ALL_ANNOUNCEMENTS: 'announcements:all',
  ANNOUNCEMENT_ITEM: (uuid: string) => `announcement:item:${uuid}`,
  ANNOUNCEMENTS_LIST: 'announcements:list',
  ALL_TALENTBASES: 'talentbases:all',
  TALENTBASE_ITEM: (uuid: string) => `talentbase:item:${uuid}`,
  TALENTBASES_LIST: 'talentbases:list',
};

export const PERFIX = {
  ALL_PROFILES: 'player_profiles:all',
  PROFILE: (uuid: string) => `player_profile:${uuid}`,
  PROFILES_LIST: 'player_profiles:list',
  ALL_OBTAINS: 'obtainbases:all',
  OBTAIN: (uuid: string) => `obtainbase:${uuid}`,
  OBTAINS_LIST: 'obtainbases:list',
  ALL_CONSUMES: 'consumebases:all',
  CONSUME: (uuid: string) => `consumebase:${uuid}`,
  CONSUMES_LIST: 'consumebases:list',
  ALL_AVATARS: 'avatarbases:all',
  AVATAR: (uuid: string) => `avatarbase:${uuid}`,
  AVATARS_LIST: 'avatarbases:list',
  ALL_FRAMES: 'framebases:all',
  FRAME: (uuid: string) => `framebase:${uuid}`,
  FRAMES_LIST: 'framebases:list',
  ALL_ANNOUNCEMENTS: 'announcements:all',
  ANNOUNCEMENT: (uuid: string) => `announcement:${uuid}`,
  ANNOUNCEMENTS_LIST: 'announcements:list',
  ALL_TALENTS: 'talentbases:all',
  TALENT: (uuid: string) => `talentbase:${uuid}`,
  TALENTS_LIST: 'talentbases:list',
};
